name: Notify about new build

on:
  release:
    types: [published, created]
  workflow_dispatch:

env:
  SLACK_AUTH_TOKEN: ${{ secrets.SLACK_AUTH_TOKEN }}

jobs:
  sendMessage:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Slack
        run: |
          message="Wallet Extension Release! *${{ github.event.release.name }}*"
          message="\n\n ${{ github.event.release.url }}"
          # message=${message//\"/\\\"} # escape double quotes
          # json='{"text":"'$message'", "icon_emoji": ":gift:", "channel": "C01HR720Q7K"}'
          json='{"text":"'$message'", "icon_emoji": ":gift:", "channel": "G017MDDTZGD"}'
          curl https://slack.com/api/chat.postMessage \
            -X POST \
            -H 'Content-type: application/json' \
            -H "Authorization: Bearer $SLACK_AUTH_TOKEN" \
            --data "$json"
